[project]
name = "impellerpy"
version = "0.1.0"
description = "Python bindings for Impeller."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.3.5",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
