name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-15 ]
    steps:
      - name: Update Submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pypa/cibuildwheel@v2.23.3
        name: Build Wheel & Test

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
