name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ macos-15 ]
    steps:
      - name: Update Submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - uses: pypa/cibuildwheel@v2.22

