name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: macos-15
    steps:
      - name: Update Dependencies
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Stat Ninja
        run: ninja
