name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: macos-15
    steps:
      - name: Update Submodules
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Autoconf
        run: brew install autoconf automake autoconf-archive
      - name: Build
        run: make
