name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Check VCPKG
        run: echo $VCPKG_INSTALLATION_ROOT
