name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Python Wheel ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # macos-13 is an Intel runner, macos-15 is Apple Silicon
        os: [ macos-13, macos-15, ubuntu-latest ]
    steps:
      - name: Update Submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt update && sudo apt install -y libwayland-dev libxkbcommon-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgles2-mesa-dev

      - name: Build Wheel
        uses: pypa/cibuildwheel@v2.23.3

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: cibw-wheel-${{ matrix.os }}-${{ strategy.job-index }}

  upload_to_test_pypy:
    name: Upload to Test PyPI
    needs: [ build_wheels ]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      # Permission for PyPy Trusted Publishing.
      # https://docs.pypi.org/trusted-publishers/
      id-token: write
    steps:
    - uses: actions/setup-python@v5
      name: Setup Python
    - uses: actions/download-artifact@v4
      name: Download Previously Built Wheels.
      with:
        path: dist
        pattern: cibw-wheel-*
        merge-multiple: true
    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true

