name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Sync Dependencies
        run: make sync
      - name: Install UV
        uses: astral-sh/setup-uv@v5
      - name: Build Default Target
        run: make
