name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_wheels:
    name: Python Wheel ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        # macos-13 is an Intel runner, macos-15 is Apple Silicon
        os: [ macos-13, macos-15 ]
    steps:
      - name: Update Submodules
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build Wheel
        uses: pypa/cibuildwheel@v2.23.3

      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  upload_all:
    name: Upload
    needs: [build_wheels]
    runs-on: ubuntu-latest
    # if: github.event_name == 'release' && github.event.action == 'published'

    steps:
    - uses: actions/setup-python@v5
      name: Setup Python
    - uses: actions/download-artifact@v4
      name: Download previously built wheels.
      with:
        path: dist
        pattern: dist-*
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        repository-url: https://test.pypi.org/legacy/

