name: Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  publish_gh_docs:
    name: Publish GitHub Docs
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install UV
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install
      - name: Deploy Docs
        run: make deploy_docs
